In [2]:
import pandas as pd

In [3]:
pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [5]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [6]:
import numpy as np

In [7]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.ones(20)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [11]:
np.full(6,9)

array([9, 9, 9, 9, 9, 9])

In [12]:
list1 = np.array([2,3,4,5,6])
list1

array([2, 3, 4, 5, 6])

In [13]:
list1[2] = 24
list1

array([ 2,  3, 24,  5,  6])

In [14]:
range1 = np.arange(10)
range1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
range2 = np.arange(3,12)
range2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
randomNumbers = np.linspace(0,100,11)
randomNumbers

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [17]:
# MULTIDIMENSIONAL ARRAYS
np.zeros((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [19]:
# reassigning the value of the item on row zero and column two
n[0][2] = 30
n
# reassigning the values of the entire row
n[0]=[10,10,10]
n

array([[10, 10, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [20]:
# this is used to get all the values in a column and its values can also be changed as shown.
n[:,2] = [5,5,5]
n

array([[10, 10,  5],
       [ 4,  5,  5],
       [ 7,  8,  5]])

In [21]:
# generating array with random numbers
# the random seed command makes sure that the random numbers generated is consistently the same even accross different devices.
np.random.seed(3)
np.random.rand(5,3)

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ],
       [0.44080984, 0.02987621, 0.45683322],
       [0.64914405, 0.27848728, 0.6762549 ]])

In [22]:
# np.random.seed(2)
np.random.randint(low=0,high=1000,size=(5,2))

array([[258, 959],
       [316, 641],
       [947, 858],
       [581, 872],
       [622, 609]])

In [23]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [24]:
a * 2

array([2, 4, 6, 8])

In [25]:
# the arry generated can be used as normal variables using PEMDAS to manipulate them.
b = (10 + (a * 2))** 2
b

array([144, 196, 256, 324])

In [26]:
a*b

array([ 144,  392,  768, 1296])

In [27]:
# comparison operators
a

array([1, 2, 3, 4])

In [28]:
a >= 2

array([False,  True,  True,  True])

In [29]:
b

array([144, 196, 256, 324])

In [30]:
(a**6) > b

array([False, False,  True,  True])

In [31]:

# this provides the output of a>b that is true. in our case none is true so the empty square brackets
(a**6)[a>b]

array([], dtype=int64)

In [32]:
# summarizing operations
# a.min()
# a.max()
# a.sum()
# a.mean()
a.std()

np.float64(1.118033988749895)

In [33]:
n.sum()

np.int64(59)

In [34]:
# VECTOT OPERATION

u = np.arange(1,8)
2 * u


array([ 2,  4,  6,  8, 10, 12, 14])

In [35]:
v= np.array([1,3,5,7,2,1,7])
w = v + u
w

array([ 2,  5,  8, 11,  7,  7, 14])

In [36]:
# VECTOR MULIPLICATION
y = u * v
y.sum()

y.shape[0]


7

In [37]:
# function that does vector to vector multiplication

def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
# this specifies the shape of the vector, the number of elements it has within it
    n = u.shape[0]

    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]


    return result

In [38]:
vector_vector_multiplication(u,v)

np.float64(115.0)

In [39]:
# there is a function that multiplies 2 vectors. the shape of each vector must be same

u.dot(v)

np.int64(115)

In [40]:
# MATRIX VECTOR MULTIPLICATION

matrix = np.array([[1,2,3,4,6],[5,6,7,8,9],[9,0,1,2,3]])
# this vector was gotten from the matrix above using the array manipulation.
# notice that the number of items(dimension) in the row of the matrix and the column of the vector are the same
vector = matrix[2]

# to get their product, multiply each row of the matrix with the column of the vector

def matrix_vector_multiplication(M,V):
    # the 1 in the square bracket is collecting the dimension for the COLUMN the 0 is for the ROW
    assert M.shape[1] == V.shape[0]

    num_rows = M.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(M[i],V)

    return result

matrix_vector_multiplication(matrix,vector)

array([38., 95., 95.])

In [41]:
# using a numpy function we have:
matrix.dot(vector)
#  the same result is gotten as above by applying the python function

array([38, 95, 95])

In [42]:
# MATRIX-MATRIX MULTIPLICATION
# note that the number of rows in the first matrix must match the number of coluns in the second matrix and the number of rows in the second matrix must match the columns in the first matrix
matrix1 = np.array([[1,2,3,4,5],[4,5,6,7,8],[5,6,7,8,9]])
matrix2 = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6],[5,6,7]])

In [43]:
def matrix_matrix_multiplication(mat1, mat2):
    assert mat1.shape[1] == mat2.shape[0]

    num_rows = mat1.shape[0]
    num_cols = mat2.shape[1]

    result = np.zeros((num_rows,num_cols))

    for i in range(num_cols):
        vi = mat2[:,i]
        Uvi = matrix_vector_multiplication(mat1,vi)
        result[:,i] = Uvi

    return result


matrix_matrix_multiplication(matrix1,matrix2)

array([[ 55.,  70.,  85.],
       [100., 130., 160.],
       [115., 150., 185.]])

In [44]:
matrix1.dot(matrix2)

array([[ 55,  70,  85],
       [100, 130, 160],
       [115, 150, 185]])

In [45]:
# THE IDENTITY MATRIX (I)

np.eye(3)
identity = np.eye(5)

matrix1.dot(identity)
identity.dot(matrix2)

array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.],
       [5., 6., 7.]])

In [46]:
# WORKING WITH PANDAS



In [47]:
data = [
       ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
       ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
       ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
      ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
       ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
    ]
columns = [
        'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
        'Transmission Type', 'Vehicle_Style', 'MSRP'
    ]
   

In [48]:
df = pd.DataFrame(data,columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [49]:
a = np.arange(2,7)
aa = a**2
aaa = a**3
aaaa= a**4

series = [[2,3,4,5,6],[3,4,5,6,7],[7,8,9,0,7],[2,5,6,4,7]]
columns = ['unitary','square','cube','quadriple','power of 5']

df  = pd.DataFrame(series,  columns=columns)
df

unitary  square  cube  quadriple  power of 5
0        2       3     4          5           6
1        3       4     5          6           7
2        7       8     9          0           7
3        2       5     6          4           7