In [280]:
import pandas as pd

In [281]:
pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [282]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [283]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [284]:
import numpy as np

In [285]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [286]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [287]:
np.ones(4)

array([1., 1., 1., 1.])

In [288]:
np.ones(20)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [289]:
np.full(6,9)

array([9, 9, 9, 9, 9, 9])

In [290]:
list1 = np.array([2,3,4,5,6])
list1

array([2, 3, 4, 5, 6])

In [291]:
list1[2] = 24
list1

array([ 2,  3, 24,  5,  6])

In [292]:
range1 = np.arange(10)
range1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [293]:
range2 = np.arange(3,12)
range2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [294]:
randomNumbers = np.linspace(0,100,11)
randomNumbers

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [295]:
# MULTIDIMENSIONAL ARRAYS
np.zeros((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [296]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [297]:
# reassigning the value of the item on row zero and column two
n[0][2] = 30
n
# reassigning the values of the entire row
n[0]=[10,10,10]
n

array([[10, 10, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [298]:
# this is used to get all the values in a column and its values can also be changed as shown.
n[:,2] = [5,5,5]
n

array([[10, 10,  5],
       [ 4,  5,  5],
       [ 7,  8,  5]])

In [299]:
# generating array with random numbers
# the random seed command makes sure that the random numbers generated a consistently the same even accross different devices.
np.random.seed(3)
np.random.rand(5,3)

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ],
       [0.44080984, 0.02987621, 0.45683322],
       [0.64914405, 0.27848728, 0.6762549 ]])

In [300]:
np.random.seed(2)
np.random.randint(low=0,high=1000,size=(5,2))

array([[168, 527],
       [493, 584],
       [534, 299],
       [466,  75],
       [360, 263]])

In [301]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [302]:
a * 2

array([0, 2, 4, 6, 8])

In [303]:
# the arry generated can be used as normal variables using PENDAS to manipulate them.
b = (10 + (a * 2))** 2

In [304]:
a*b

array([   0,  144,  392,  768, 1296])

In [305]:
# comparison operators
a

array([0, 1, 2, 3, 4])

In [306]:
a >= 2

array([False, False,  True,  True,  True])

In [307]:
b

array([100, 144, 196, 256, 324])

In [308]:
a > b

array([False, False, False, False, False])

In [309]:

# this provides the output of a>b that is true. in our case none is true so the empty square brackets
a[a>b]

array([], dtype=int64)

In [317]:
# summarizing operations
# a.min()
# a.max()
# a.sum()
# a.mean()
a.std()

np.float64(1.4142135623730951)

In [318]:
n.sum()

np.int64(59)