In [1]:
import pandas as pd
import numpy as np

In [2]:
# QUESTION 1
pd.__version__


'2.3.1'

In [3]:
pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [5]:
# QUESTION 2
# there are 9704 records in the table

df.index

RangeIndex(start=0, stop=9704, step=1)

In [6]:
# QUESTION 3
# there are 2 fuel types in the table

df['fuel_type'].nunique()

2

In [7]:
# QUESTION 4
# there are 4 columns that have missing

columns_with_null_elements = df.isnull().sum() 
number_of_columns = columns_with_null_elements[columns_with_null_elements > 0]
number_of_columns



num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64

In [8]:
# QUESTION 5
# what is the maximum fuel efficiency for cars from asia rounded to 2 dp
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max().round(2)



np.float64(23.76)

In [9]:
# QUESTION 6

#1 median value of horse power
df['horsepower'].median()

np.float64(149.0)

In [10]:
#2 most frequent value in the horsepower column
df['horsepower'].mode()[0]

np.float64(152.0)

In [11]:
#3  using fillna to fill the missing data in the horsepower column
df['horsepower'] = df['horsepower'].fillna(152)
df['horsepower']

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [12]:
#4  calculate the new median of the horsepower column
df['horsepower'].median()


np.float64(152.0)

In [13]:
#  QUESTION 6 APPRAISAL QUESTION.
# has the median value changed?
# YES, IT INCREASED.

In [14]:
# QUESTION 7
# 1 SELECT ALL THE CARS IN ASIA
cars_from_Asia = df['origin'] == 'Asia'

In [15]:
# 2. select only columns vehicle_weight and model_year
vehicle_weight_and_model_year = df[['vehicle_weight','model_year']]
vehicle_weight_and_model_year



vehicle_weight  model_year
0        3413.433759        2003
1        3149.664934        2007
2        3079.038997        2018
3        2542.392402        2009
4        3460.870990        2009
...              ...         ...
9699     2981.107371        2013
9700     2439.525729        2004
9701     2583.471318        2008
9702     2905.527390        2011
9703     2908.043477        2005

[9704 rows x 2 columns]

In [16]:
# 3 SELECTING THE FIRST 7 VALUES FROM THE CREATED TABLE

new_table = vehicle_weight_and_model_year.head(7)

In [17]:
# 4. GET THE UNDERLYING NUMPY ARRAY

x = new_table.values
x

array([[3413.43375861, 2003.        ],
       [3149.66493422, 2007.        ],
       [3079.03899737, 2018.        ],
       [2542.39240183, 2009.        ],
       [3460.87098999, 2009.        ],
       [2484.88398604, 2008.        ],
       [3006.54228722, 2012.        ]])

In [18]:
#  5.Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose,  use X.T. Let's call the result XTX.

transpose_x = x.T

XTX = transpose_x.dot(x)
XTX



array([[64707732.45267162, 42471352.31816065],
       [42471352.31816065, 28264752.        ]])

In [19]:
# 6 INVERT XTX

XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 1.12464107e-06, -1.68991495e-06],
       [-1.68991495e-06,  2.57468996e-06]])

In [20]:
# 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [21]:
# 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w = (XTX_inverse.dot(transpose_x)).dot(y)
w



array([0.07099685, 0.41931263])

In [22]:
# 9. What's the sum of all the elements of the result?
w.sum()

np.float64(0.4903094879707426)